In [31]:
import numpy as np

In [32]:
my_list = [1, 2, 3] # Python list
type(my_list)

list

In [33]:
my_arr = np.array(my_list) # convertion de la list python en array numpy
my_arr

array([1, 2, 3])

In [34]:
type(my_arr) 

numpy.ndarray

In [35]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # creation d'une matrice 3x3 avec une list python
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [36]:
np.array(my_matrix) # convertion de la matrice python en array numpy 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.arange(0, 10) # creation d'un array numpy avec la fonction arange au lieu de la fonction range de python

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])