In [35]:
import numpy as np

In [36]:
my_list = [1, 2, 3] # Python list
type(my_list)

list

In [37]:
my_arr = np.array(my_list) # convertion de la list python en array numpy
my_arr

array([1, 2, 3])

In [38]:
type(my_arr) 

numpy.ndarray

In [39]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # creation d'une matrice 3x3 avec une list python
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [40]:
np.array(my_matrix) # convertion de la matrice python en array numpy 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.arange(0, 101, 10) # creation d'un array numpy avec la fonction arange au lieu de la fonction range de python et un pas de 2

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [42]:
np.zeros(3) # creation d'un array numpy de 3 zeros

array([0., 0., 0.])

In [43]:
np.zeros((3, 5)) # creation d'un array numpy de 3x5 zeros (ligne, colonne)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.ones((4,4)) # creation d'un array numpy de 4x4 de 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.linspace(125, 456, 11) # creation d'un array numpy de 11 valeurs entre 125.523 et 456.5
# len(np.linspace(125, 456, 11)) # verification du nombre de valeurs (ici 11)

array([125. , 158.1, 191.2, 224.3, 257.4, 290.5, 323.6, 356.7, 389.8,
       422.9, 456. ])

In [46]:
np.eye(4) # creation d'un array numpy de 4x4 avec des 1 sur la diagonale

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.random.rand(5,2) # creation d'un array numpy de 5x2 avec des valeurs aleatoires entre 0 et 1

array([[0.03131329, 0.84228477],
       [0.44975413, 0.39515024],
       [0.92665887, 0.727272  ],
       [0.32654077, 0.57044397],
       [0.52083426, 0.96117202]])

In [48]:
np.random.randn(5,2) # creation d'un array numpy de 5x2 avec des valeurs aleatoires selon une distribution normale

array([[ 0.47319325,  0.6591906 ],
       [ 2.34074633,  1.07098519],
       [ 0.09641648,  0.41910211],
       [-0.95302779, -1.0478706 ],
       [-1.87567677, -1.36678214]])

In [49]:
np.random.randint(0, 101, (4,5)) # creation d'un array numpy de 4x5 avec des valeurs aleatoires entre 0 et 100

array([[ 7, 87, 62, 10, 80],
       [ 7, 34, 34, 32,  4],
       [40, 27,  6, 72, 71],
       [11, 33, 32, 47, 22]])

In [50]:
np.random.seed(42) # creation d'un seed pour avoir toujours les memes valeurs aleatoires
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [51]:
np.random.rand(4) # on a toujours les memes valeurs aleatoires car on a fixe le seed au dessus 

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [52]:
np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [53]:
arr = np.arange(0,25) # creation d'un array numpy de 25 valeurs
arr.reshape(5,5) # on reshape l'array numpy en 5x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
ranarr = np.random.randint(0, 101, 10) # creation d'un array numpy de 10 valeurs aleatoires entre 0 et 100
ranarr

array([29, 37,  1, 63, 59, 20, 32, 75, 57, 21])

In [55]:
ranarr.max() # on recupere la valeur max de l'array numpy

75

In [56]:
ranarr.min() # on recupere la valeur min de l'array numpy

1

In [57]:
ranarr.argmax() # on recupere l'index de la valeur max de l'array numpy

7

In [58]:
ranarr.argmin() # on recupere l'index de la valeur min de l'array numpy

2

In [59]:
ranarr.dtype # on recupere le type de l'array numpy

dtype('int32')

In [60]:
arr.shape # on recupere la forme de l'array numpy

(25,)

In [61]:
arr = arr.reshape(5,5) # on reshape l'array numpy en 5x5
arr.shape # on recupere la forme de l'array numpy

(5, 5)

In [62]:
arr.reshape(1,25) # on reshape l'array numpy en 1x25

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])