In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3] # Python list
type(my_list)

list

In [3]:
my_arr = np.array(my_list) # convertion de la list python en array numpy
my_arr

array([1, 2, 3])

In [4]:
type(my_arr) 

numpy.ndarray

In [5]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # creation d'une matrice 3x3 avec une list python
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix) # convertion de la matrice python en array numpy 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 101, 10) # creation d'un array numpy avec la fonction arange au lieu de la fonction range de python et un pas de 2

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [8]:
np.zeros(3) # creation d'un array numpy de 3 zeros

array([0., 0., 0.])

In [9]:
np.zeros((3, 5)) # creation d'un array numpy de 3x5 zeros (ligne, colonne)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((4,4)) # creation d'un array numpy de 4x4 de 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(125, 456, 11) # creation d'un array numpy de 11 valeurs entre 125.523 et 456.5
# len(np.linspace(125, 456, 11)) # verification du nombre de valeurs (ici 11)

array([125. , 158.1, 191.2, 224.3, 257.4, 290.5, 323.6, 356.7, 389.8,
       422.9, 456. ])

In [12]:
np.eye(4) # creation d'un array numpy de 4x4 avec des 1 sur la diagonale

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5,2) # creation d'un array numpy de 5x2 avec des valeurs aleatoires entre 0 et 1

array([[0.41224089, 0.10159991],
       [0.26818353, 0.22499828],
       [0.40979155, 0.83690987],
       [0.04032493, 0.92608818],
       [0.10110523, 0.6715021 ]])

In [14]:
np.random.randn(5,2) # creation d'un array numpy de 5x2 avec des valeurs aleatoires selon une distribution normale

array([[-0.53623306, -0.36391239],
       [-0.30734482, -0.38712304],
       [ 0.259367  , -0.68362362],
       [-0.47332407,  0.8440921 ],
       [ 1.07559222,  0.73061891]])

In [15]:
np.random.randint(0, 101, (4,5)) # creation d'un array numpy de 4x5 avec des valeurs aleatoires entre 0 et 100

array([[ 10,  47,  40,  83,   2],
       [100,  97,  77,  78,  16],
       [ 71,  77,  70,  29,  36],
       [ 22,  88,  22,  48,  73]])

In [16]:
np.random.seed(42) # creation d'un seed pour avoir toujours les memes valeurs aleatoires
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [17]:
np.random.rand(4) # on a toujours les memes valeurs aleatoires car on a fixe le seed au dessus 

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [18]:
np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [19]:
arr = np.arange(0,25) # creation d'un array numpy de 25 valeurs
arr.reshape(5,5) # on reshape l'array numpy en 5x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ranarr = np.random.randint(0, 101, 10) # creation d'un array numpy de 10 valeurs aleatoires entre 0 et 100
ranarr

array([29, 37,  1, 63, 59, 20, 32, 75, 57, 21])

In [21]:
ranarr.max() # on recupere la valeur max de l'array numpy

75

In [22]:
ranarr.min() # on recupere la valeur min de l'array numpy

1

In [23]:
ranarr.argmax() # on recupere l'index de la valeur max de l'array numpy

7

In [24]:
ranarr.argmin() # on recupere l'index de la valeur min de l'array numpy

2

In [25]:
ranarr.dtype # on recupere le type de l'array numpy

dtype('int32')

In [26]:
arr.shape # on recupere la forme de l'array numpy

(25,)

In [27]:
arr = arr.reshape(5,5) # on reshape l'array numpy en 5x5
arr.shape # on recupere la forme de l'array numpy

(5, 5)

In [28]:
arr.reshape(1,25) # on reshape l'array numpy en 1x25

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])